### PR TITLE
Ft rework landing page

### PR DESCRIPTION
**Pull request by meshnesh**
# What does this PR do?

Redesigns and changes the look and feel of the landing page the application.

# How should this be manually tested?

* Clone the project to your local machine,
* Install the dependancies from the `requirements.txt` file.
* Run the application `python manage.py runserver`.
* open the application from the url given and preview the page.

### Screenshots

screen shot 2018-05-30 at 19 26 30
screen shot 2018-05-30 at 19 26 51
screen shot 2018-05-30 at 19 27 12
screen shot 2018-05-30 at 19 27 23
screen shot 2018-05-30 at 19 27 34

##### Pivotal tracker
Relevant stories: [#157110858](https://www.pivotaltracker.com/story/show/157110858)

### CODE REVIEW

**Review by Kalela — APPROVED** [review]
LGTM

**Review by betsybeth — APPROVED** [review]
Good work.The background colors LGTM

**Review by FelixWambiri — APPROVED** [review]
Good work on the implementation especially on the theme.

**Review by mutoromike — APPROVED** [review]
I like the theme! Great job!!

**Review by frankip — CHANGES_REQUESTED** [review]
I love the theme and look
Fix the conflicts

**Pull request merged**
