### PR TITLE
#157110843 Ft Add Fitbit Support 

### PR DESCRIPTION
**Pull request by mutoromike**
**What does this PR do??**

Fixes dashboard button location

screen shot 2018-05-21 at 10 51 29

**What are related Pivotal Tracker stories?**

Story: Add Fitbit support
ID: #157110843

### CODE REVIEW

**Review by meshnesh — CHANGES_REQUESTED** [review]
Fix conflicting files && ask for reviewers

**Review by frankip — DISMISSED** [review]
you have conflicting files fix them

**Review by Kalela — CHANGES_REQUESTED** [review]
Do you think the button would look better if it was a bit nearer to the ``` Add weight entry ```? I think it would feel a lot more intuitive for the user if it was next to ``` Add weight entry ```

**Comment by mutoromike** [comment]
@Kalela, Kindly have a look at the whole page layout and comment on the bottom row that holds the buttons:
screen shot 2018-05-21 at 11 21 29

The point was to have uniformity in button spacing.

**Comment by Kalela** [comment]
@mutoromike Isn't adding weight a different input from nutrition plans and workouts? and fitbit support and adding weight in the same 'department' ?

**Review by meshnesh — APPROVED** [review]

**Comment by mutoromike** [comment]
Have a look at the new buttons:
screen shot 2018-05-21 at 11 49 03

**Review by betsybeth — APPROVED** [review]
The buttons look good

**Review by FelixWambiri — APPROVED** [review]
Nice implementation and I think its in sync with the rest of the page layout

**Review by frankip — APPROVED** [review]
I like the button spacing and placement 
👍

**Review by Kalela — APPROVED** [review]

**Pull request merged**
