### PR TITLE
#157110846 making translations of exercises and ingredients easier

### PR DESCRIPTION
**Pull request by mutoromike**
**What does this PR do?**

Adds new dashboard functionality for a user to change the language depending on their preferences.

screen shot 2018-05-03 at 12 14 11

**What are the relevant pivotal tracker stories?**

Make translations of exercises and ingredients easier 
ID: #157110846

### CODE REVIEW

**Comment by betsybeth** [comment]
I think you can try and centre langauges in the dropdown-menu

**Comment by Kalela** [comment]
Actually @betsybeth . I had a conversation with Elton. He said all form text should be to the left. You can check with most professional websites.

**Review by FelixWambiri — COMMENTED** [review]
Nice work and implementation

**Review by meshnesh — CHANGES_REQUESTED** [review]
Please add padding to the languages to remove them from the touching the border of the div

**Review by frankip — COMMENTED** [review]
LGTM

**Comment by mutoromike** [comment]
Thanks for the review guys. An adjustment has been done and the following is the outcome:
screen shot 2018-05-03 at 19 33 15

**Review by meshnesh — APPROVED** [review]
good implementing the changes

**Review by betsybeth — APPROVED** [review]
Good work on styling the dropdown menu

**Pull request merged**
