### PR TITLE
Enable social logins #157110859

### PR DESCRIPTION
**Pull request by betsybeth**
What does this Pr do?
Remove the print statement in setting_global.py
Remove social login for Facebook

### CODE REVIEW

**Review by FelixWambiri — COMMENTED** [review]
Please solve the travis errors, Nice implementation though

**Review by FelixWambiri — APPROVED** [review]
LGTM

**Review by Kalela — APPROVED** [review]
LGTM

**Review by frankip — APPROVED** [review]
👍 
LGTM

**Review by meshnesh — APPROVED** [review]

**Review by mutoromike — APPROVED** [review]
LGTM

**Pull request merged**
