### PR TITLE
Ft user states

### PR DESCRIPTION
**Pull request by FelixWambiri**
**Description of Task to be completed?**
*  To list only active members in the default list and have a second overview page for the deactivated ones.

**How should this be manually tested?**
* Login as an admin with password admin
* Create a new gym and give it a name of your choice
* Add a few members to the gym.
* As an administrator use your permissions to deactivate a few users. 
* Go back to gym overview and click on the all, active and deactivated buttons to view all users.

**What are the relevant pivotal tracker stories?**
* #157110839

**Background context**
* At the moment, the only way to determine whether a gym member is active or not is to open his detail view.

**Screenshots**
* Default page which also happens to show all users.
image

* Page showing Active users after the active users button is clicked
image

* Page showing inactive users after clicking the deactivated users button.
image

### CODE REVIEW

**Review by meshnesh — CHANGES_REQUESTED** [review]
Nice implementation of the feature and completing the task.
Please run `flake8` in your application to note the changes to make the build to pass so that it can be approved.

**Review by mutoromike — COMMENTED** [review]
Great work implementing the task! What do you think of making the "DEACTIVATED" users button red, it could really add some emotion.

**Review by betsybeth — CHANGES_REQUESTED** [review]
Good work on the task I think you should change the deactivated users button to color red

**Review by meshnesh — APPROVED** [review]
Nice fixing the build errors

**Review by betsybeth — APPROVED** [review]
LGTM.

**Comment by FelixWambiri** [comment]
@betsybeth and @mutoromike.One point of correction, the reason as to why the deactivated users button is not red is that its function is just to list deactivated users and not activate them.If it was the one that was clicked to deactivate them, I would have made it red

**Pull request merged**
