### PR TITLE
Ft allow creation user rest api

### PR DESCRIPTION
**Pull request by betsybeth**
What does this PR do?
It fixs fixtures

### CODE REVIEW

**Review by Kalela — APPROVED** [review]
LGTM

**Comment by mutoromike** [comment]
Kindly request more reviewers.

**Review by FelixWambiri — COMMENTED** [review]
Nice work on solving the errors.Could you try to fix the coveralls so that the check passes.

**Review by FelixWambiri — APPROVED** [review]
It looks good to me

**Review by mutoromike — APPROVED** [review]
LGTM

**Comment by betsybeth** [comment]
@FelixWambiri The tests have decreased due to the database config url that i added and I am trying to figure out how to test it  or to increase the coverage with no success.Any help I will appreciate

**Review by meshnesh — APPROVED** [review]

**Pull request merged**
