### PR TITLE
Ft user states

### PR DESCRIPTION
**Pull request by FelixWambiri**
**Description of Task to be completed?**
* Fix errors occurring when deploying to Heroku and incorporate the changes from develop branch. 

**How should this be manually tested?**
* Login as an admin with password admin
* Create a new gym and give it a name of your choice
* Add a few members to the gym.
* As an administrator use your permissions to deactivate a few users. 
* Go back to gym overview and click on the all, active and deactivated buttons to view all users.

**What are the relevant pivotal tracker stories?**
* #157507861

**Background context**
* At the moment this feature is failing with an error on Heroku as some changes have not been incorporated.

### CODE REVIEW

**Review by mutoromike — APPROVED** [review]

**Review by Kalela — APPROVED** [review]
LGTM

**Review by meshnesh — APPROVED** [review]

**Review by meshnesh — CHANGES_REQUESTED** [review]
fix conflicting files

**Review by meshnesh — APPROVED** [review]

**Review by betsybeth — APPROVED** [review]
Good work in resolving failing tests to enable passing of travis

**Review by frankip — CHANGES_REQUESTED** [review]
You should remove the settings file, and push

**Review by frankip — APPROVED** [review]

**Pull request merged**
