### PR TITLE
#157110847 ft relationship between workouts and logs

### PR DESCRIPTION
**Pull request by mutoromike**
**What does this PR do?**
 Creates a relationship between workout sessions and workout logs by adding a foreign key to workout sessions.

**Related Pivotal Tracker Stories**
Relation between workout log and session
ID: #157110847

### CODE REVIEW

**Review by meshnesh — APPROVED** [review]
nice implementation of the foreign key implementation

**Review by FelixWambiri — APPROVED** [review]
LGTM

**Review by betsybeth — APPROVED** [review]

**Review by Kalela — APPROVED** [review]
LGTM

**Review by frankip — APPROVED** [review]
Good Work

**Pull request merged**
