### PR TITLE
Heroku docker image deployment

### PR DESCRIPTION
**Pull request by meshnesh**
# What does this PR do?

* This PR allows the application to be deployed to heroku and people can use it.

## How should this be manually tested?

Navigate to [Heroku](https://wg-bigas-opus.herokuapp.com/en/dashboard) and view the application

### Relevant pivotal story

[#157310675](https://www.pivotaltracker.com/story/show/157310675)

### CODE REVIEW

**Review by frankip — DISMISSED** [review]
the registration on heroku as issues, i can neither register nor login as the admin. please fix them

**Review by betsybeth — APPROVED** [review]
LGTM.
Good work in using docker

**Review by frankip — APPROVED** [review]
it works good online 
LGTM

**Review by FelixWambiri — APPROVED** [review]
Nice work on the implementation especially deploying docker.

**Review by mutoromike — APPROVED** [review]
LGTM

**Review by Kalela — APPROVED** [review]
LGTM

**Review by lakivisi-zz — APPROVED** [review]

**Pull request merged**
