### PR TITLE
#157110848 Allow comparison of members

### PR DESCRIPTION
**Pull request by frankip**
#### What does this PR do?
allows two users to compare their weight 
#### Description of Task to be completed?
When two users are training together it would be useful to see a comparison of some sorts. A possibility would be to have a graph where the data for (selected) members is shown.
#### How should this be manually tested?
After cloning checkout to `ft-memeber-comparison` then navigate to the weight and add new weight. add several weigh. Navigate to the comparison tab there you will see a graph. if there was another user you can select the user and compare their graph also.
#### What are the relevant pivotal tracker stories?
[157110848](https://www.pivotaltracker.com/story/show/157110848)

#### Screenshots
screen shot 2018-05-30 at 21 51 13

screen shot 2018-05-30 at 21 51 57

### CODE REVIEW

**Review by meshnesh — APPROVED** [review]
good implementation of d3 js and comparison of the weights

**Review by mutoromike — APPROVED** [review]
LGTM

**Review by Kalela — APPROVED** [review]

**Review by FelixWambiri — COMMENTED** [review]
Nice Implementation. Try to improve the test coverage though.

**Review by betsybeth — APPROVED** [review]
LGTM

**Pull request merged**
