### PR TITLE
Revert "Fixed conflicting migrations"

### PR DESCRIPTION
**Pull request by betsybeth**
What does this PR have?
Fixed migration files

### CODE REVIEW

**Review by meshnesh — APPROVED** [review]

**Review by mutoromike — APPROVED** [review]
LGTM

**Comment by lakivisi-zz** [comment]
@frankip @FelixWambiri @Kalela Approve this request

**Review by Kalela — APPROVED** [review]
LGTM

**Review by FelixWambiri — APPROVED** [review]
LGTM

**Review by frankip — APPROVED** [review]
👍 
LGTM

**Pull request merged**
